#!/usr/bin/env python3.7
import pickle
import json


with open('nonadj_lehmer.pickle', 'rb') as fp:
    nonadj = pickle.load(fp)

with open('equivalents_lehmer.pickle', 'rb') as fp:
    equivs = pickle.load(fp)

data = {'nodes': list(), 'links': list()}
pull = {p: len(s) for p, s in nonadj.items()}
processed = set()

for p, s in nonadj.items():
    if pull[p] > 0:
        data['nodes'].append({'id': str(p), 'value': pull[p], 'equivs': equivs[p]})
    for q in s:
        if q not in processed:
            data['links'].append({'source': str(p), 'target': str(q), 'value': pull[p] + pull[q]})
    processed.add(p)

with open('nonadj_graph.json', 'w') as fp:
    json.dump(data, fp, indent=4)
    fp.write('\n')
